"""
generator.py
Turns the JSON config produced by index.html into a downloadable ZIP containing
a self-contained python-telegram-bot (v21+) project.

Public entrypoint:
    generate_bot_zip(config: dict, uploads_dir: str | None = None) -> bytes

Design: instead of code-generating bespoke Python per trigger/action, we ship
one generic "engine" (bot.py) plus a data file (config.json) that the engine
interprets at runtime. This keeps generation simple and the output easy for a
user to read/tweak by hand.
"""

import base64
import io
import json
import os
import re
import uuid
import zipfile
from typing import Optional

DATA_URI_RE = re.compile(r"^data:([^;]+);base64,(.*)$", re.DOTALL)


def _guess_ext(mime: str, fallback: str = ".bin") -> str:
    mapping = {
        "image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp", "image/gif": ".gif",
        "video/mp4": ".mp4", "video/quicktime": ".mov",
        "audio/mpeg": ".mp3", "audio/ogg": ".ogg", "audio/wav": ".wav",
        "application/pdf": ".pdf",
    }
    return mapping.get(mime, fallback)


def _resolve_asset(zf: zipfile.ZipFile, assets_seen: dict, value: Optional[str], uploads_dir: Optional[str]) -> Optional[str]:
    """
    Normalizes a media field's value into something the generated bot can use:
      - already an http(s) URL          -> left as-is, Telegram fetches it directly
      - a data: URI (inline base64)     -> decoded and written into assets/
      - a local "/media/<name>" path    -> copied from uploads_dir into assets/
      - empty/None                      -> None

    Returns the string to store in config.json, or None.
    """
    if not value:
        return None

    if value.startswith("http://") or value.startswith("https://"):
        return value

    m = DATA_URI_RE.match(value)
    if m:
        mime, b64data = m.group(1), m.group(2)
        if value in assets_seen:
            return assets_seen[value]
        try:
            raw = base64.b64decode(b64data)
        except Exception:
            return None
        fname = f"assets/{uuid.uuid4().hex}{_guess_ext(mime)}"
        zf.writestr(fname, raw)
        assets_seen[value] = fname
        return fname

    if value.startswith("/media/") and uploads_dir:
        local_name = value.split("/media/", 1)[1]
        local_path = os.path.join(uploads_dir, local_name)
        if value in assets_seen:
            return assets_seen[value]
        if os.path.isfile(local_path):
            fname = f"assets/{local_name}"
            with open(local_path, "rb") as f:
                zf.writestr(fname, f.read())
            assets_seen[value] = fname
            return fname
        return None

    # Unknown scheme — pass through untouched, engine will try to use it as-is.
    return value


MEDIA_ACTION_FIELDS = {
    "send_photo": "url", "send_video": "url", "send_document": "url",
    "send_voice": "url", "send_sticker": "url",
}


def _rewrite_config_assets(zf: zipfile.ZipFile, config: dict, uploads_dir: Optional[str]) -> dict:
    assets_seen: dict = {}
    out = json.loads(json.dumps(config))  # deep copy
    for trigger in out.get("triggers", []):
        for action in trigger.get("actions", []):
            field = MEDIA_ACTION_FIELDS.get(action.get("type"))
            if not field:
                continue
            params = action.get("params", {})
            resolved = _resolve_asset(zf, assets_seen, params.get(field), uploads_dir)
            params[field] = resolved
            # drop the upload-UI-only bookkeeping fields if present
            for junk_key in (field + "_name", field + "_size", field + "_uploading"):
                params.pop(junk_key, None)
    return out


BOT_PY = r'''"""
Auto-generated by the bot constructor. This is a generic engine that reads
config.json and drives a python-telegram-bot Application from it — it does
not need to be regenerated if you tweak config.json by hand.
"""
import asyncio
import json
import logging
import os
from pathlib import Path

from dotenv import load_dotenv
from telegram import (
    InlineKeyboardButton, InlineKeyboardMarkup,
    KeyboardButton, ReplyKeyboardMarkup, ReplyKeyboardRemove,
    LabeledPrice, Update,
)
from telegram.constants import ChatAction
from telegram.ext import (
    Application, ApplicationBuilder, CommandHandler, CallbackQueryHandler,
    ChatMemberHandler, ContextTypes, MessageHandler, PreCheckoutQueryHandler, filters,
)

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
log = logging.getLogger("bot")

BASE_DIR = Path(__file__).resolve().parent
CONFIG = json.loads((BASE_DIR / "config.json").read_text(encoding="utf-8"))
TRIGGERS = CONFIG.get("triggers", [])
KEYBOARDS = {kb["id"]: kb for kb in CONFIG.get("keyboards", [])}

BOT_TOKEN = os.environ.get("BOT_TOKEN")
if not BOT_TOKEN:
    raise SystemExit("Set BOT_TOKEN in your .env file first (see .env.example).")

# Per-chat runtime state.
pending_ask: dict[int, dict] = {}   # chat_id -> {"trigger_idx", "action_idx", "varname"}
variables: dict[int, dict] = {}     # chat_id -> {varname: value}


def build_markup(keyboard_id):
    if not keyboard_id or keyboard_id not in KEYBOARDS:
        return None
    kb = KEYBOARDS[keyboard_id]
    if kb["type"] == "inline":
        rows = []
        for row in kb["rows"]:
            line = []
            for b in row:
                if b["type"] == "url" and b.get("value"):
                    line.append(InlineKeyboardButton(b["text"], url=b["value"]))
                elif b["type"] == "bot_action":
                    line.append(InlineKeyboardButton(b["text"], callback_data=b.get("value") or b["text"]))
                elif b["type"] == "stars_payment":
                    line.append(InlineKeyboardButton(b["text"], callback_data=f"__pay__:{b.get('value') or ''}"))
            if line:
                rows.append(line)
        return InlineKeyboardMarkup(rows) if rows else None
    else:
        rows = []
        for row in kb["rows"]:
            line = []
            for b in row:
                if b["type"] == "request_contact":
                    line.append(KeyboardButton(b["text"], request_contact=True))
                elif b["type"] == "request_location":
                    line.append(KeyboardButton(b["text"], request_location=True))
                else:
                    line.append(KeyboardButton(b["text"]))
            if line:
                rows.append(line)
        return ReplyKeyboardMarkup(rows, resize_keyboard=True) if rows else None


def fmt(text: str, chat_id: int) -> str:
    """Fills {varname} placeholders using variables saved by ask_and_save."""
    if not text:
        return text
    ctx_vars = variables.get(chat_id, {})
    try:
        return text.format(**ctx_vars)
    except Exception:
        return text


async def run_actions(actions: list, start_idx: int, trigger_idx: int, update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat_id = update.effective_chat.id
    for i in range(start_idx, len(actions)):
        action = actions[i]
        a_type = action.get("type")
        p = action.get("params", {}) or {}
        markup = build_markup(action.get("keyboard_id"))

        try:
            if a_type == "send_message":
                await context.bot.send_message(chat_id, fmt(p.get("text", ""), chat_id), reply_markup=markup)

            elif a_type in ("send_photo", "send_video", "send_document", "send_voice", "send_sticker"):
                ref = p.get("url")
                media = open(BASE_DIR / ref, "rb") if ref and not ref.startswith("http") else ref
                caption = fmt(p.get("caption", "") or "", chat_id) or None
                if a_type == "send_photo":
                    await context.bot.send_photo(chat_id, media, caption=caption, reply_markup=markup)
                elif a_type == "send_video":
                    await context.bot.send_video(chat_id, media, caption=caption, reply_markup=markup)
                elif a_type == "send_document":
                    await context.bot.send_document(chat_id, media, caption=caption, reply_markup=markup)
                elif a_type == "send_voice":
                    await context.bot.send_voice(chat_id, media, reply_markup=markup)
                elif a_type == "send_sticker":
                    await context.bot.send_sticker(chat_id, media, reply_markup=markup)

            elif a_type == "request_contact":
                kb = ReplyKeyboardMarkup(
                    [[KeyboardButton(p.get("text") or "Отправить контакт", request_contact=True)]],
                    resize_keyboard=True, one_time_keyboard=True,
                )
                await context.bot.send_message(chat_id, p.get("text") or "Поделитесь, пожалуйста, контактом", reply_markup=kb)

            elif a_type == "request_location":
                kb = ReplyKeyboardMarkup(
                    [[KeyboardButton(p.get("text") or "Отправить геолокацию", request_location=True)]],
                    resize_keyboard=True, one_time_keyboard=True,
                )
                await context.bot.send_message(chat_id, p.get("text") or "Поделитесь, пожалуйста, геолокацией", reply_markup=kb)

            elif a_type == "ask_and_save":
                await context.bot.send_message(chat_id, fmt(p.get("text", ""), chat_id))
                pending_ask[chat_id] = {
                    "trigger_idx": trigger_idx,
                    "action_idx": i + 1,
                    "varname": p.get("varname") or "answer",
                }
                return  # wait for the user's reply before resuming

            elif a_type == "pause":
                await asyncio.sleep(float(p.get("seconds") or 1))

            elif a_type == "typing":
                await context.bot.send_chat_action(chat_id, ChatAction.TYPING)

            elif a_type == "delete_message":
                if update.message:
                    try:
                        await update.message.delete()
                    except Exception:
                        pass

            elif a_type == "send_invoice":
                await context.bot.send_invoice(
                    chat_id=chat_id,
                    title=p.get("title") or "Оплата",
                    description=p.get("description") or "-",
                    payload=f"order_{chat_id}_{i}",
                    provider_token="",  # empty for Telegram Stars
                    currency="XTR",
                    prices=[LabeledPrice(p.get("title") or "Товар", int(p.get("price") or 1))],
                )

            elif a_type == "remove_keyboard":
                await context.bot.send_message(chat_id, "Клавиатура скрыта.", reply_markup=ReplyKeyboardRemove())

        except Exception as e:
            log.exception("Action %s failed: %s", a_type, e)


def trigger_matches(trigger: dict, update: Update) -> bool:
    t = trigger["type"]
    msg = update.effective_message
    if t == "command":
        return False  # commands are registered as dedicated CommandHandlers
    if t == "text_equals":
        return bool(msg and msg.text and msg.text == (trigger.get("value") or ""))
    if t == "text_contains":
        return bool(msg and msg.text and (trigger.get("value") or "") in msg.text)
    if t == "photo_received":
        return bool(msg and msg.photo)
    if t == "video_received":
        return bool(msg and msg.video)
    if t == "voice_received":
        return bool(msg and msg.voice)
    if t == "document_received":
        return bool(msg and msg.document)
    if t == "location_received":
        return bool(msg and msg.location)
    if t == "contact_received":
        return bool(msg and msg.contact)
    if t == "any_message":
        return bool(msg)
    return False


async def on_any_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    chat_id = update.effective_chat.id

    pending = pending_ask.get(chat_id)
    if pending:
        del pending_ask[chat_id]
        msg = update.effective_message
        value = msg.text if msg and msg.text else (msg.caption if msg else None)
        variables.setdefault(chat_id, {})[pending["varname"]] = value or ""
        trigger = TRIGGERS[pending["trigger_idx"]]
        await run_actions(trigger.get("actions", []), pending["action_idx"], pending["trigger_idx"], update, context)
        return

    # Skip triggers with type "command" and "callback" here — handled elsewhere.
    # Try specific (non any_message) triggers first, then fall back to any_message.
    specific = [t for t in TRIGGERS if t["type"] not in ("command", "callback", "any_message", "new_chat_member")]
    for idx, trigger in enumerate(TRIGGERS):
        if trigger in specific and trigger_matches(trigger, update):
            await run_actions(trigger.get("actions", []), 0, idx, update, context)
            return
    for idx, trigger in enumerate(TRIGGERS):
        if trigger["type"] == "any_message":
            await run_actions(trigger.get("actions", []), 0, idx, update, context)
            return


async def on_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    data = query.data or ""
    for idx, trigger in enumerate(TRIGGERS):
        if trigger["type"] == "callback" and (trigger.get("value") or "") == data:
            await run_actions(trigger.get("actions", []), 0, idx, update, context)
            return


async def on_new_chat_member(update: Update, context: ContextTypes.DEFAULT_TYPE):
    for idx, trigger in enumerate(TRIGGERS):
        if trigger["type"] == "new_chat_member":
            await run_actions(trigger.get("actions", []), 0, idx, update, context)
            return


async def on_precheckout(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.pre_checkout_query.answer(ok=True)


def make_command_handler(idx: int):
    async def _handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
        await run_actions(TRIGGERS[idx].get("actions", []), 0, idx, update, context)
    return _handler


def build_app() -> Application:
    app = ApplicationBuilder().token(BOT_TOKEN).build()

    for idx, trigger in enumerate(TRIGGERS):
        if trigger["type"] == "command" and trigger.get("value"):
            app.add_handler(CommandHandler(trigger["value"], make_command_handler(idx)))

    app.add_handler(CallbackQueryHandler(on_callback))
    app.add_handler(ChatMemberHandler(on_new_chat_member, ChatMemberHandler.CHAT_MEMBER))
    app.add_handler(MessageHandler(filters.StatusUpdate.NEW_CHAT_MEMBERS, on_new_chat_member))
    app.add_handler(PreCheckoutQueryHandler(on_precheckout))
    app.add_handler(MessageHandler(filters.ALL & ~filters.COMMAND, on_any_message))

    return app


if __name__ == "__main__":
    application = build_app()
    log.info("Bot starting (polling mode)...")
    application.run_polling(allowed_updates=Update.ALL_TYPES)
'''

REQUIREMENTS_TXT = "python-telegram-bot==21.4\npython-dotenv==1.0.1\n"

ENV_EXAMPLE = "BOT_TOKEN=\n"

README_MD = """# Твой бот

Сгенерировано конструктором ботов.

## Запуск

1. Установи зависимости:
   ```
   pip install -r requirements.txt
   ```
2. Скопируй `.env.example` в `.env` и впиши токен от @BotFather:
   ```
   BOT_TOKEN=123456:AA...
   ```
3. Запусти бота:
   ```
   python bot.py
   ```

Бот работает в режиме long polling — не нужен ни вебхук, ни публичный сервер.
Все триггеры, действия и клавиатуры лежат в `config.json` — их можно
редактировать вручную, `bot.py` перечитывать не нужно (просто перезапусти
процесс).
"""


def generate_bot_zip(config: dict, uploads_dir: Optional[str] = None) -> bytes:
    """
    Builds the full bot project as a ZIP and returns it as bytes.

    `uploads_dir` should be the same folder /api/upload_media saves into, so
    any "/media/<file>" references in the config can be embedded as local
    assets in the generated project.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        resolved_config = _rewrite_config_assets(zf, config, uploads_dir)

        zf.writestr("bot.py", BOT_PY)
        zf.writestr("config.json", json.dumps(resolved_config, ensure_ascii=False, indent=2))
        zf.writestr("requirements.txt", REQUIREMENTS_TXT)
        zf.writestr(".env.example", ENV_EXAMPLE)
        zf.writestr("README.md", README_MD)

    return buf.getvalue()
